// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "./components/Footer";
import AuthProvoider from "@/context/AuthProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-sky-100 to-indigo-300">
        <Navbar />
        <AuthProvoider>{children}</AuthProvoider>
        <Footer />
      </body>
    </html>
  );
}
